AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple Todo Application
Resources:
  Create:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create
      Runtime: go1.x
      CodeUri: ./build
      Timeout: 5
      MemorySize: 1024
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        CreateEvent:
          Type: Api
          Properties:
            Path: /todos
            Method: post
  DELETE:
    Type: AWS::Serverless::Function
    Properties:
      Handler: delete
      Runtime: go1.x
      CodeUri: ./build
      Timeout: 5
      MemorySize: 1024
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        CreateEvent:
          Type: Api
          Properties:
            Path: /todos/{id}
            Method: DELETE
  Index:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index
      Runtime: go1.x
      CodeUri: ./build
      Timeout: 5
      MemorySize: 1024
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Table
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        CreateEvent:
          Type: Api
          Properties:
            Path: /todos
            Method: get
  Show:
    Type: AWS::Serverless::Function
    Properties:
      Handler: show
      Runtime: go1.x
      CodeUri: ./build
      Timeout: 5
      MemorySize: 1024
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Table
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        CreateEvent:
          Type: Api
          Properties:
            Path: /todos/{id}
            Method: get
  Update:
    Type: AWS::Serverless::Function
    Properties:
      Handler: update
      Runtime: go1.x
      CodeUri: ./build
      Timeout: 5
      MemorySize: 1024
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        CreateEvent:
          Type: Api
          Properties:
            Path: /todos/{id}
            Method: PATCH
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: ID
        Type: String
      GlobalSecondaryIndexes:
        - IndexName: ByComplete
          KeySchema:
            - AttributeName: Completed
              KeyType: Boolean
        - IndexName: ByCompletedAt
          KeySchema:
            - AttributeName: Completed
              KeyType: HASH
            - AttributeName: UpdatedAt
              KeyType: RANGE
      BillingMode:
        Mode: OnDemand

  
